apiVersion: v1
kind: Service
metadata:
  name: {{ include "platypus.fullname" . }}
  labels:
    {{- include "platypus.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.config.port }}
      protocol: TCP
      name: luceneserver
  selector:
    {{- include "platypus.selectorLabels" . | nindent 4 }}
